### ISSUE TITLE
[BUG]: Possible Security Issue

### ISSUE THREAD

**Issue by Lyssers** [wasi-master/wasi-master.github.io#2]
### Description of the bug

Hello,

I am a big fan of 13ft and have my own instance running as well! Very cool. You're amazing making stuff like this at 17.

One thing I've discovered though is that because the request resolution and retrieval and subsequent parsing of the HTML is done server-side, it allows one to access internal resources on the network reachable by the server.

For example, on my instance, I am able to reach my local server's SSH port, despite it not being exposed to the internet

![image](https://github.com/user-attachments/assets/6ad204fa-b15f-4eb8-9393-8361bce1a0f0)

This leaks information about the SSH version for instance.

Or I could even access entire internal websites this way, like Jellyfin for instance:

![image](https://github.com/user-attachments/assets/c8ff9c15-af7f-4eed-9a62-3bf90b174a25)

Here it is displaying in-browser:

![image](https://github.com/user-attachments/assets/2f969f9f-3051-4e42-863b-2c16eaa664db)

Or even my gateway/router:

![image](https://github.com/user-attachments/assets/2781f0f6-91ce-4650-b86d-74db97c5f6dd)

None of these are publicly accessible normally, but because with 13ft requests come from the server, it essentially functions as a reverse-nginx, where all requests to it are forwarded into the local network.

I was able to do the same thing on the public instance linked to the repo and obtain SSH version

![Screenshot_20240904_134825](https://github.com/user-attachments/assets/1808a144-8a42-4ce9-9a66-c0f7bba565e3)

Only it was worse because I no longer had to guess the IPs, as I was able to simply use localhost. I was not able to use localhost on my instance because it would resolve to Docker's internal IP, not letting me access much outside of that.

But on your instance, by simply changing the port I was able to find a default apache page on port 80 and determine the nginx version and confirm the existence of a database.

On Shodan there are many more instances where this is noticeable:

![image](https://github.com/user-attachments/assets/e9a23015-6dee-4031-ab8b-673c3dae95fa)

Arguably this is an issue and a server-side forgery

Furthermore, there's also a problem with how the end result is wrapped in HTML in case of an error.

![image](https://github.com/user-attachments/assets/9789cee8-d6ad-46c4-bd43-1b5805fbb925)

It is very trivial to bypass the parsing and force a "Failed to Parse" error, in which case the Javascript will run:

![image](https://github.com/user-attachments/assets/2d4b976f-f2d5-4892-98ed-fbcf40529164)

Considering the nature of 13ft as a proxy, it is possible to perform cross site scripting inclusion attacks, all one has to do is go to someone's public instance and paste the link to their (attacker) server hosting malicious JS, turning the thing into a CSS machine, then simply distribute such a link to unsuspecting users and collect potentially sensitive info.

### Steps To Reproduce

1. Go to any 13ft instance accessible publicly
2. Into the link field, input a private IP address (e.g. 192.168.0.1 as is common for consumer grade routers) that can be resolved, or IP of another server.
(Sidenote) - If using cloudflare, HSTS will block most anything that is not HTTPS, so either use an HTTP version of the instance or point it to an HTTPS URL.
3. Observe how the private IP and resource are now accessible.

**Comment by wasi-master** [comment]
Thanks for the very detailed issue. Really appreciate it! I'll put out a fix as soon as I can. 

I currently don't have a foolproof solution to the first issue of accessing other locally hosted pages but for the instance I'm hosting I'm just gonna switch it to run in a docker container and that should help. I could also do something to detect local IP ranges and disallow them but I'm still not sure about this.

For the second problem of css attacks I'll just sanitize the html and that should be the end of it.

**Comment by Lyssers** [comment]
Yeah it's a bit of a doozy. I'm actually fairly sure 12ft.io has this too, but it's hard to tell.

Actually with docker, it would still be possible to access the gateway (which is the host of docker in this case), because it's often fairly deterministically 172.17.0.1, with only the second octet changing if one is running more than 1 docker container network e.g. 172.18.0.1

I suppose you could do that, and then use regex to match for 172.* anything. Or one could match any digits followed by dots and digits with regex like \d+\.\d+

But that's also easily bypassed: https://book.hacktricks.xyz/pentesting-web/ssrf-server-side-request-forgery/url-format-bypass

I think the solution is to just have a disclaimer, like https://github.com/everywall/ladder that tells people to put it behind auth. Your choice! Good luck and thanks for reading my report.
